---
- name: IBM i test playbook
  hosts: "{{ ibmiserver | default(['172.16.13.58']) }}"

  vars:
        cur_become_user: IBMECS
        repo_server: 172.16.13.58
        # ptf_group: SF99750
        # ptf_group_number: SF99750

  tasks:
        - name: Fetch objlib libary on a remote IBM i to local, store as /backup/objlib.file.
          ibm.power_ibmi.ibmi_fetch:
                lib_name: 'testlib'
                dest: './backup'
                flat: true
