# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# ibmi-fix-repo-lv1.yml
# Provide example for manipulating a level 1 PTF database
---
- name: Playbook example for IBM i fix management
  hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi
  vars:
    ptf_group_number: 'SF99750'

  tasks:
    - name: Initialize check_ptf_group_fail
      ansible.builtin.set_fact:
        fix_repo_check_ptf_group_check_ptf_group_fail: false

    - name: Check and get the latest PTF group information on PSP
      ibm.power_ibmi.ibmi_fix_group_check:
        groups: '{{ ptf_group_number }}'
      register: fix_repo_check_ptf_group_fix_group_check_result

- name: Print the latest PTF group information
  ansible.builtin.debug:
    var: fix_repo_check_ptf_group_fix_group_check_result

- name: Check for failure
  when: fix_repo_check_ptf_group_fix_group_check_result.group_info is not defined
  block:
    - name: If cannot get the latest PTF group information, then fail
      ansible.builtin.debug:
        msg: "Get the latest PTF group information fail, skip the rest of this role"

    - name: Set check_ptf_group_fail to True
      ansible.builtin.set_fact:
        fix_repo_check_ptf_group_check_ptf_group_fail: true

- name: Perform checking
  when: fix_repo_check_ptf_group_fix_group_check_result.group_info is defined
  block:
    - name: Check if PTF group information is already in catalog's PTF group information table
      ibm.power_ibmi.ibmi_fix_repo:
        type: "ptf_group"
        action: "find"
        parameters:
          - "{{ {'ptf_group_number': fix_repo_check_ptf_group_fix_group_check_result.group_info[0].ptf_group_number,
          'ptf_group_level': fix_repo_check_ptf_group_fix_group_check_result.group_info[0].ptf_group_level,
          'release_date': fix_repo_check_ptf_group_fix_group_check_result.group_info[0].release_date} }}"
      register: fix_repo_check_ptf_group_ptf_group_find_result
      when: fix_repo_check_ptf_group_fix_group_check_result.group_info != []

    - name: Print find PTF group result
      ansible.builtin.debug:
        var: fix_repo_check_ptf_group_ptf_group_find_result

    - name: Checking download status table
      when: fix_repo_check_ptf_group_ptf_group_find_result.fail_list is defined
      block:
        - name: Check if PTF group information is already in catalog's download_status table, which means PTF group is downloading.
          ibm.power_ibmi.ibmi_fix_repo:
            type: "download_status"
            action: "find"
            parameters:
              - "{{ {'ptf_group_number': fix_repo_check_ptf_group_fix_group_check_result.group_info[0].ptf_group_number,
              'ptf_group_level': fix_repo_check_ptf_group_fix_group_check_result.group_info[0].ptf_group_level,
              'release_date': fix_repo_check_ptf_group_fix_group_check_result.group_info[0].release_date} }}"
          register: fix_repo_check_ptf_group_download_status_find_result
          when: fix_repo_check_ptf_group_fix_group_check_result.group_info != []

        - name: Print find download_status table result
          ansible.builtin.debug:
            var: fix_repo_check_ptf_group_download_status_find_result
    # Role for fix_repo_check_ptf_group
    # Get the latest PTF group information from PSP(Preventive Service Planning) server, 
    # and check if the latest PTF group is already in ptf_group_image table or already downloading.
    
    - name: Include IBM i role fix_repo_download_add_ptf_group
      ansible.builtin.include_role:
        name: fix_repo_download_add_ptf_group
      vars:
        ptf_id: "SF99750"

    # Role for fix_repo_download_add_ptf_group
    # Call ibm.power_ibmi.ibmi_download_fix module to download ptf group,
    # then call ibm.power_ibmi.ibmi_fix_repo module to add information into download_status table in catalog.        

    - name: Task drop_the_table
      ibm.power_ibmi.ibmi_fix_repo_lv1:
        action: "clear"
