# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# ibmi-fix-repo-lv1.yml
# Provide example for manipulating a level 1 PTF database
---
- name: Playbook example for IBM i fix management
  hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
    - name: Include IBM i role fix_repo_check_ptf_group
      ansible.builtin.include_role:
        name: ibm.power_ibmi.fix_repo_check_ptf_group
      vars:
        fix_repo_check_ptf_group_ptf_group: "SF99750"
    
    # Role for fix_repo_check_ptf_group
    # Get the latest PTF group information from PSP(Preventive Service Planning) server, 
    # and check if the latest PTF group is already in ptf_group_image table or already downloading.
    
    - name: Include IBM i role fix_repo_download_add_ptf_group
      ansible.builtin.include_role:
        name: fix_repo_download_add_ptf_group
      vars:
        fix_repo_download_add_ptf_group_ptf_group_info.ptf_group_number: "SF99750"

    # Role for fix_repo_download_add_ptf_group
    # Call ibm.power_ibmi.ibmi_download_fix module to download ptf group,
    # then call ibm.power_ibmi.ibmi_fix_repo module to add information into download_status table in catalog.        

    - name: Task drop_the_table
      ibm.power_ibmi.ibmi_fix_repo_lv1:
        action: "clear"
