---
- name: Install fixes by image catalog
  hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
    fix_install_path: "{{ fix_install_path }}"

  tasks:
    - name: Install selected fixes from image catalog
      ibm.power_ibmi.ibmi_fix_imgclg:
        src: '{{ fix_install_path }}'
        apply_type: '*DLYALL'
        hiper_only: False
        use_temp_path: False
        rollback: True
        become_user: "QSECOFR"
        become_user_password: "PASSWORD"
      register: fix_install_path_info

    - name: Display selected fixes installed information
      ansible.builtin.debug:
        msg: '{{ fix_install_path_info }}'