---
- name: Playbook with CL command examples
  hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi      

  tasks:
    - name: Run the CL command to create a library
      ibmi_cl_command:
        cmd: crtlib lib(ansiblei)
      register: crt_lib_result

    - name: Display crtlib debug message text
      ansible.builtin.debug:
        msg: 
          - "rc: {{ crt_lib_result.rc }}"
          - "cmd: {{ crt_lib_result.cmd }}"
          - "msgid: {{ crt_lib_result.job_log[0].MESSAGE_ID }}"
          - "msgtype: {{ crt_lib_result.job_log[0].MESSAGE_TYPE }}"
          - "msgtxt: {{ crt_lib_result.job_log[0].MESSAGE_TEXT }}"      

    - name: Run the CL command to create the library again
      ibmi_cl_command:
        cmd: crtlib lib(ansiblei)
        joblog: true
      register: crt_lib_repeated_result
      ignore_errors: true

    - name: Display crtlib again debug message text
      ansible.builtin.debug:
        msg: 
          - "rc: {{ crt_lib_repeated_result.rc }}"
          - "cmd: {{ crt_lib_repeated_result.cmd }}"
          - "msgid: {{ crt_lib_repeated_result.job_log[0].MESSAGE_ID }}"
          - "msgtype: {{ crt_lib_repeated_result.job_log[0].MESSAGE_TYPE }}"
          - "msgtxt: {{ crt_lib_repeated_result.job_log[0].MESSAGE_TEXT }}"

    - name: Assert the repeating creation of the library failed
      ansible.builtin.assert:
        that:
          - (crt_lib_repeated_result.job_log | selectattr('MESSAGE_ID', 'equalto', 'CPF2111') | map(attribute='MESSAGE_ID') | list | length) >= 1

    - name: Run the CL command to delete the library
      ibmi_cl_command:
        cmd: dltlib lib(ansiblei)
        joblog: true
      register: dlt_lib_result

    - name: Display dltlib debug message text
      ansible.builtin.debug:
        msg:
          - "rc: {{ dlt_lib_result.rc }}"
          - "cmd: {{ dlt_lib_result.cmd }}"
          - "msgid: {{ dlt_lib_result.job_log[0].MESSAGE_ID }}"
          - "msgtype: {{ dlt_lib_result.job_log[0].MESSAGE_TYPE }}"
          - "msgtxt: {{ dlt_lib_result.job_log[0].MESSAGE_TEXT }}"

