---
- name: Playbook with CL command examples
  hosts: all
  gather_facts: false
  collections:
    - name: ibm.power_ibmi      

  tasks:
    - name: Run the CL command to create a library
      ibm.power_ibmi.ibmi_cl_command:
        cmd: crtlib lib(ansiblei)
      register: crt_lib_result

    - name: Run the CL command to create the library again
      ibmi_cl_command:
        cmd: crtlib lib(ansiblei)
        joblog: true
      register: crt_lib_repeated_result
      ignore_errors: true

    - name: Assert the repeating creation of the library failed
      ansible.builtin.assert:
        that:
          - (crt_lib_repeated_result.job_log | selectattr('MESSAGE_ID', 'equalto', 'CPF2111') | map(attribute='MESSAGE_ID') | list | length) >= 1

    - name: Run the CL command to delete the library
      ibm.power_ibmi.ibmi_cl_command:
        cmd: dltlib ansiblei
        joblog: false
