# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# ibmi-fix-check.yml
# Provide examples on the use of ibmi_fix_check
---
- name: Example playbook on the use of ibmi_fix_check
  hosts: all
  gather_facts: false

  tasks:
    - name: Task download ptf through SNDPTFORD
      ibm.power_ibmi.ibmi_download_fix:
        delivery_format: '*IMAGE'
        order: '*REQUIRED'
        ptf_id: '*CUMGRP'
        reorder: '*NO'
