---
- name: Playbook examples
  hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
    - name: IBM i check a set of groups
      ansible.builtin.include_role:
        name: check_ptf_groups_against_fix_repo
    
    - name: print groups status
      debug: 
        var: check_ptf_groups_against_fix_repo_group_status

    - name: Retrieve the latest PTF group information from PSP server
      ibmi_fix_check:
        groups: "{{ ptf_group_number }}"
      register: fix_check_result
    
    - name: Display the fix_check_result
      ansible.builtin.debug: 
        msg: 
          - "rc: {{ fix_check_result.rc | int }}"
          - "group_info: {{ fix_check_result.group_info }}"

    - name: Do module authority check
      ibm.power_ibmi.ibmi_module_authority_check:
        modulelist:
          - 'ibmi_copy'
          - 'ibmi_display_subsystem'
          - 'ibmi_invaild_module'
      register: module_authority_check_return

    - name: Display module authority check return debug info
      ansible.builtin.debug:
        msg: "{{ module_authority_check_return.authority_result }}"

    - name: Run the CL command to create a library
      ibm.power_ibmi.ibmi_cl_command:
        cmd: crtlib lib(ansiblei)
        joblog: true
      register: crt_lib_result

    - name: Display crtlib debug message text
      ansible.builtin.debug:
        msg: 
          - "rc: {{ crt_lib_result.rc | int }}"
          - "cmd: {{ crt_lib_result.cmd }}"
          - "msgid: {{ crt_lib_result.job_log[0].MESSAGE_ID }}"
          - "msgtype: {{ crt_lib_result.job_log[0].MESSAGE_TYPE }}"
          - "msgtxt: {{ crt_lib_result.job_log[0].MESSAGE_TEXT }}"      

    - name: Run the CL command to create the library again
      ibmi_cl_command:
        cmd: crtlib lib(ansiblei)
        joblog: true
      register: crt_lib_repeated_result
      ignore_errors: true

    - name: Display crtlib again debug message text
      ansible.builtin.debug:
        msg: 
          - "rc: {{ crt_lib_repeated_result.rc | int }}"
          - "cmd: {{ crt_lib_repeated_result.cmd }}"
          - "msgid: {{ crt_lib_repeated_result.job_log[0].MESSAGE_ID }}"
          - "msgtype: {{ crt_lib_repeated_result.job_log[0].MESSAGE_TYPE }}"
          - "msgtxt: {{ crt_lib_repeated_result.job_log[0].MESSAGE_TEXT }}"

    - name: Assert the repeating creation of the library failed
      ansible.builtin.assert:
        that:
          - (crt_lib_repeated_result.job_log | selectattr('MESSAGE_ID', 'equalto', 'CPF2111') | map(attribute='MESSAGE_ID') | list | length) >= 1

    - name: Run the CL command to delete the library
      ibmi_cl_command:
        cmd: dltlib lib(ansiblei)
        joblog: true
      register: dlt_lib_result

    - name: Display dltlib debug message text
      ansible.builtin.debug:
        msg:
          - "rc: {{ dlt_lib_result.rc | int }}"
          - "cmd: {{ dlt_lib_result.cmd }}"
          - "msgid: {{ dlt_lib_result.job_log[0].MESSAGE_ID }}"
          - "msgtype: {{ dlt_lib_result.job_log[0].MESSAGE_TYPE }}"
          - "msgtxt: {{ dlt_lib_result.job_log[0].MESSAGE_TEXT }}"

