# Parameter example:
# 'download_fix_status_order_list': 'Order_list_number'

---
- name: Check fix download status
  hosts: all
  gather_facts: false
  collections:
    ibm.power_ibmi

  vars:
    download_fix_status_order_list: '{{ download_fix_status_order_list }}'

  tasks:
    - name: Checking whether the fix downloading complete
      ibmi_download_fix_status:
        order_list: '{{ download_fix_status_order_list }}'
        become_user: "QSECOFR"
        become_user_password: "PASSWORD"
      register: download_fix_status_info

    - name: Display fix downloading check status
      ansible.builtin.debug:
        msg: "{{ download_fix_status_info.msg.status[0].download_status }}"

