- name: IBM i fix mgmt
  hosts: ibmi75

  vars:
      fix_repo_check_ptf_group_fix_group_check_result: "SF99750"
      fix_repo_check_ptf_group_ptf_group_find_result:
      fix_repo_check_ptf_group_download_status_find_result:
      fix_repo_check_ptf_group_check_ptf_group_fail:

  tasks:
      - name: Include fix_repo_check_ptf_group role to check if the latest ptf group is already in catalog
        ansible.builtin.include_role:
            name: fix_repo_check_ptf_group_ptf_group

#  - name: Check ptf group currency
#    ansible.builtin.include_role:
#       name: check_ptfs_by_product_against_fix_repo
#  - name: Print ptf group Status
#    ansible.builtin.debug:
#      var: check_ptf_groups_against_fix_repo_group_status


# - name: Find http webserver
#   ansible.builtin.shell:
#     cmd: yum search nginx
#
# - name: Install http webserver
#   ansible.builtin.shell:
#     cmd: yum install nginx -y
#
#  - name: Remove http webserver
#    ansible.builtin.shell:
#      cmd: yum erase nginx -y
